class Settings:
    N_LAYERS_MIN = 1
    N_LAYERS_MAX = 100

    HIDDEN_UNITS_MIN = 1
    HIDDEN_UNITS_MAX = 100

    LEARNING_RATE_MIN = 0.00001
    LEARNING_RATE_MAX = 0.2

    DROPOUT_RATE_MIN = 0
    DROPOUT_RATE_MAX = 1
